### ISSUE TITLE
测试发现以下问题

### ISSUE THREAD

**Issue by mysterywolf** [loogg/agile_ftp#1]
1.无法重命名
2.无法完整复制文件夹（内含文件s） 复制一半会报错

我是用的是windows自带的，创建了一个ftp网络
![image](https://user-images.githubusercontent.com/34888354/119378567-fac01f80-bcf0-11eb-8c14-a704b4c501f9.png)

使用filezilla也会有这个问题

**Comment by loogg** [comment]
我好像都没遇到过，明晚有空的话开个远程我看看



---原始邮件---
发件人: "Meco Jianting ***@***.***&gt;
发送时间: 2021年5月25日(周二) 凌晨0:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [loogg/agile_ftp] 测试发现以下问题 (#1)




 
1.无法重命名
 2.无法删除文件
 3.无法完整复制文件夹（内含文件s）

**Comment by loogg** [comment]
这个关闭吧？
